name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      skip_tests:
        description: 'Skip running tests'
        required: false
        default: false
        type: boolean
      skip_deploy:
        description: 'Skip deployment (build only)'
        required: false
        default: false
        type: boolean

jobs:
  test-backend:
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip_tests }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: backend/yarn.lock
    
    - name: Install backend dependencies
      working-directory: ./backend
      run: yarn install --frozen-lockfile
    
    - name: Run backend tests
      working-directory: ./backend
      run: yarn test
    
    - name: Build backend
      working-directory: ./backend
      run: yarn build

  test-frontend:
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip_tests }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: frontend/yarn.lock
    
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: yarn install --frozen-lockfile
    
    - name: Build frontend
      working-directory: ./frontend
      run: yarn build

  build-docker:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip_tests }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build backend Docker image
      run: docker build -t real-time-bid-backend ./backend
    
    - name: Build frontend Docker image
      run: docker build -t real-time-bid-frontend ./frontend
    
    - name: Run Docker Compose
      run: docker-compose up -d --build

  build-docker-skip-tests:
    runs-on: ubuntu-latest
    if: ${{ inputs.skip_tests }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build backend Docker image
      run: docker build -t real-time-bid-backend ./backend
    
    - name: Build frontend Docker image
      run: docker build -t real-time-bid-frontend ./frontend
    
    - name: Run Docker Compose
      run: docker-compose up -d --build

  deploy-backend:
    needs: [build-docker, build-docker-skip-tests]
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip_deploy && inputs.environment == 'production' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v1.0.0
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}

  deploy-frontend:
    needs: [build-docker, build-docker-skip-tests]
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip_deploy && inputs.environment == 'production' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./frontend 